blueprint:
  name: Motion Light
  description: Turn on lights when motion or occupancy is detected. Optionally check if it's dark. Turn off after a timeout.
  domain: automation
  input:
    motion_sensor:
      name: Motion or Occupancy Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class:
              - motion
              - occupancy

    light_target:
      name: Light Target
      selector:
        target:
          entity:
            domain: light

    timeout:
      name: Time to wait before turning off (no motion)
      selector:
        duration: {}

    use_dark_time:
      name: Use Dark-Time Condition
      description: Only turn on lights when it's dark
      default: true
      selector:
        boolean: {}

    dark_time_sensor:
      name: Binary Sensor for Dark Time
      description: This sensor must be "on" for the automation to activate lights if enabled.
      default: binary_sensor.dark_time
      selector:
        entity:
          filter:
            domain: binary_sensor

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input timeout
    id: nomotion

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not !input use_dark_time }}"
      - condition: state
        entity_id: !input dark_time_sensor
        state: "on"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion
        sequence:
          - service: light.turn_on
            target: !input light_target
      - conditions:
          - condition: trigger
            id: nomotion
        sequence:
          - service: light.turn_off
            target: !input light_target

mode: single
