blueprint:
  name: Motion-activated Light with Optional Dark-Time Condition
  description: Turn on lights when motion or occupancy is detected. Optionally restrict to dark time. Turn off after a timeout.
  domain: automation
  input:
    motion_sensor:
      name: Motion or Occupancy Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class:
              - motion
              - occupancy
    light_target:
      name: Light or Switch Target
      selector:
        target: {}
    timeout:
      name: Time to wait before turning off (no motion)
      selector:
        duration: {}
    use_dark_time:
      name: Use Dark-Time Condition
      description: Only turn on lights when it's dark
      default: false
      selector:
        boolean: {}
    dark_time_sensor:
      name: Binary Sensor for Dark Time
      default: binary_sensor.dark_time
      selector:
        entity:
          filter:
            domain: binary_sensor

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input timeout
    id: nomotion

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not (input.use_dark_time | default(false)) }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_target
              - conditions:
                  - condition: template
                    value_template: "{{ input.use_dark_time | default(false) }}"
                  - condition: state
                    entity_id: !input dark_time_sensor
                    state: "on"
                sequence:
                  - service: light.turn_on
                    target: !input light_target
      - conditions:
          - condition: trigger
            id: nomotion
        sequence:
          - service: light.turn_off
            target: !input light_target

mode: single
